version: '3.7'

services:
  pgbouncer1:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer1
    hostname: pgbouncer1
    networks:
      - bouncer-backend
    ports:
      - "6433:5432"
    environment:
      TZ: "${TZ}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      POOL_MODE: "${POOL_MODE}"
      MAX_CLIENT_CONN: "${MAX_CLIENT_CONN}"
      DEFAULT_POOL_SIZE: "${DEFAULT_POOL_SIZE}"
      MAX_DB_CONNECTIONS: "${MAX_DB_CONNECTIONS}"
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-h', 'localhost' ]

  pgbouncer2:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer2
    hostname: pgbouncer2
    networks:
      - bouncer-backend
    ports:
      - "6434:5432"
    environment:
      TZ: "${TZ}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      POOL_MODE: "${POOL_MODE}"
      MAX_CLIENT_CONN: "${MAX_CLIENT_CONN}"
      DEFAULT_POOL_SIZE: "${DEFAULT_POOL_SIZE}"
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-h', 'localhost' ]

  pgbouncer3:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer3
    hostname: pgbouncer3
    networks:
      - bouncer-backend
    ports:
      - "6435:5432"
    environment:
      TZ: "${TZ}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      POOL_MODE: "${POOL_MODE}"
      MAX_CLIENT_CONN: "${MAX_CLIENT_CONN}"
      DEFAULT_POOL_SIZE: "${DEFAULT_POOL_SIZE}"
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-h', 'localhost' ]

  haproxy:
    image: haproxytech/haproxy-alpine:latest
    #build:
    #  context: haproxy
    #image: haproxy:1.0
    container_name: haproxy
    hostname: haproxy
    networks:
      - bouncer-backend
    privileged: true
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "6432:6432"
      - "8404:8404"
networks:
  bouncer-backend:
